name: Build Agent
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-go
            mingw-w64-x86_64-libvpx

      - name: Build agent
        shell: msys2 {0}
        run: |
          go mod tidy
          go build -tags "vp8enc" cmd/agent.go
          
      - name: Copy binaries
        shell: msys2 {0}
        run: |
          mkdir out
          cp agent.exe out/

          BINDIR="out"
          EXE="$BINDIR/agent.exe"

          paths=("/mingw64/bin")

          function findAndCopyDLL() {
              for i in "${paths[@]}"
              do
                  FILE="$i/$1"
                  if [ -f $FILE ]; then
                     cp $FILE $BINDIR
                     echo "Found $1 in $i"
                     copyForOBJ $FILE
                     return 0
                  fi
              done

              return 1
          }

          function copyForOBJ() {
              dlls=`objdump -p $1 | grep 'DLL Name:' | sed -e "s/\t*DLL Name: //g"`
              while read -r filename; do
                  findAndCopyDLL $filename || echo "Unable to find $filename"
              done <<< "$dlls"
          }

          copyForOBJ $EXE
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: agent-binaries
          path: out/*
